# Use a MongoDB image as the base image
FROM mongo:latest

# Copy the mongo import script to a directory that is automatically executed by the mongod process when the container starts up
COPY mongo-init.js /docker-entrypoint-initdb.d/

# Set environment variables for the script
ENV MONGO_INITDB_ROOT_USERNAME=root
ENV MONGO_INITDB_ROOT_PASSWORD=example

# Set the working directory to /data/db
WORKDIR /data/db